/**
 * @file Automatically generated by barrelsby.
 */

import * as Enginets from "./Engine";
import * as Utilsts from "./Utils";
import * as eventsEventSystemts from "./events/EventSystem";
import * as eventsIEngineEventsts from "./events/IEngineEvents";
import * as eventsIGameEventsts from "./events/IGameEvents";
import * as eventsIUIEventsts from "./events/IUIEvents";
import * as gameGamets from "./game/Game";
import * as gameIGamets from "./game/IGame";
import * as gamesystemSystemts from "./game/system/System";
import * as gamesystemSystemControllerts from "./game/system/SystemController";
import * as modulesModuleManagerts from "./modules/ModuleManager";
import * as typests from "./types";
import * as uiUIts from "./ui/UI";
import * as uiUITypests from "./ui/UITypes";
import * as uicomponentsGameCardts from "./ui/components/GameCard";
import * as uicomponentsSVGButtonts from "./ui/components/SVGButton";
import * as uicomponentsTextButtonts from "./ui/components/TextButton";
import * as uicomponentsbasicAppScreents from "./ui/components/basic/AppScreen";
import * as uicomponentsbasicAppWindowts from "./ui/components/basic/AppWindow";
import * as uicomponentsbasicBackgroundts from "./ui/components/basic/Background";
import * as uicomponentsbasicButtonts from "./ui/components/basic/Button";
import * as uicomponentsbasicSVGGraphicsts from "./ui/components/basic/SVGGraphics";
import * as uicomponentsbasicTintts from "./ui/components/basic/Tint";
import * as uicomponentscontrollersScenesControllerts from "./ui/components/controllers/ScenesController";
import * as uicomponentscontrollersWindowsControllerts from "./ui/components/controllers/WindowsController";
import * as uicomponentsscenesGameScenets from "./ui/components/scenes/GameScene";
import * as uicomponentsscenesLoadScenets from "./ui/components/scenes/LoadScene";
import * as uicomponentsscenesMenuScenets from "./ui/components/scenes/MenuScene";
import * as uicomponentsscenesResultScenets from "./ui/components/scenes/ResultScene";
import * as uicomponentssceneswrapperIntroScenets from "./ui/components/scenes/wrapper/IntroScene";
import * as uicomponentswindowsInfoWindowts from "./ui/components/windows/InfoWindow";
import * as uicomponentswindowsPauseWindowts from "./ui/components/windows/PauseWindow";
export {Enginets as Engine};
export {Utilsts as Utils};
export const events = {
  EventSystem: eventsEventSystemts,
  IEngineEvents: eventsIEngineEventsts,
  IGameEvents: eventsIGameEventsts,
  IUIEvents: eventsIUIEventsts,
};
export const game = {
  Game: gameGamets,
  IGame: gameIGamets,
  system: {
    System: gamesystemSystemts,
    SystemController: gamesystemSystemControllerts,
  },
};
export const modules = {
  ModuleManager: modulesModuleManagerts,
};
export {typests as types};
export const ui = {
  UI: uiUIts,
  UITypes: uiUITypests,
  components: {
    GameCard: uicomponentsGameCardts,
    SVGButton: uicomponentsSVGButtonts,
    TextButton: uicomponentsTextButtonts,
    basic: {
      AppScreen: uicomponentsbasicAppScreents,
      AppWindow: uicomponentsbasicAppWindowts,
      Background: uicomponentsbasicBackgroundts,
      Button: uicomponentsbasicButtonts,
      SVGGraphics: uicomponentsbasicSVGGraphicsts,
      Tint: uicomponentsbasicTintts,
    },
    controllers: {
      ScenesController: uicomponentscontrollersScenesControllerts,
      WindowsController: uicomponentscontrollersWindowsControllerts,
    },
    scenes: {
      GameScene: uicomponentsscenesGameScenets,
      LoadScene: uicomponentsscenesLoadScenets,
      MenuScene: uicomponentsscenesMenuScenets,
      ResultScene: uicomponentsscenesResultScenets,
      wrapper: {
        IntroScene: uicomponentssceneswrapperIntroScenets,
      },
    },
    windows: {
      InfoWindow: uicomponentswindowsInfoWindowts,
      PauseWindow: uicomponentswindowsPauseWindowts,
    },
  },
};
