fileGroups:
  wrapper-assetpack:
    - /packages/shared/assetpack/wrapper.ts

  game-assetpack:
    - /packages/shared/assetpack/game.ts

  library-sources:
    - "src/**/*"
    - "rslib.config.ts"
    - "/packages/shared/rspack/library.config.ts"

  game-sources:
    - "src/**/*"
    - "assets/**/*"
    - "package.json"
    - "tsconfig.json"
    - "rspack.config.ts"
    - "moon.yml"
    - "/packages/shared/html/game.index.html"
    - "/packages/shared/rspack/base.config.ts"
    - "/packages/shared/rspack/game.config.ts"
    - "/packages/shared/rspack/game-react.config.ts"
    - "/packages/shared/normalize/normalize.css"
    - "/packages/shared/assetpack/game.ts"
    - "/packages/shared/assetpack/base.ts"

  wrapper-sources:
    - "src/**/*"
    - "rspack.config.ts"
    - "public/**/*"
    - "assets/wrapper.json"
    - "/packages/shared/rspack/base.config.ts"
    - "/packages/shared/rspack/wrapper.config.ts"
