inheritedBy:
  # All projects with layer application will get this tasks
  layers: ["application"]

tasks:
  # Build
  build-assets:
    command: bunx --bun assetpack -c @files(game-assetpack)
    inputs:
      - "assets/**/*"
      - "/packages/shared/assetpack/game.ts"
      - "/packages/shared/assetpack/base.ts"
    outputs:
      - "dist/assets/**/*"
    options:
      internal: true
  build-sources:
    command: bunx --bun rspack build
    deps:
      - ^:build
      - ~:build-assets
    inputs:
      - "@group(game-sources)"
    outputs:
      - "dist"
    options:
      internal: true
  build:
    toolchains: ["bun"]
    deps:
      - ~:build-sources
    inputs:
      - "@group(game-sources)"

  # Dev
  dev-assets:
    # @files(game-assetpack) is a path to assetpack config from all.yml
    command: bunx --bun assetpack -w -c @files(game-assetpack)
    options:
      # Run in parallel
      persistent: true
      # Logs won't work without it
      outputStyle: stream
      internal: true
  dev-sources:
    command: bunx --bun rspack serve
    deps:
      # depends on dev from all packages in `dependsOn` array
      - ^:dev
    options:
      persistent: true
      outputStyle: stream
      internal: true
  dev:
    toolchains: ["bun"]
    deps:
      # depends on dev-assets here
      - ~:dev-assets
      # and dev-sources also here
      - ~:dev-sources
    options:
      persistent: true
    inputs:
      # React on changes in @group(game-sources) files
      - "@group(game-sources)"
