inheritedBy:
  layers: ["library"]

tasks:
  build:
    command: "bunx rslib"
    toolchains: ["bun"]
    deps:
      - ^:build
    inputs:
      - "@group(library-sources)"
    outputs:
      - "dist"
  dev:
    command: "bunx rslib -w --env-mode dev"
    toolchains: ["bun"]
    options:
      persistent: true
      # Hide from user, it will run automatically
      internal: true
    deps:
      - ^:dev
    inputs:
      - "@group(library-sources)"
