inheritedBy:
  layers: ["tool"]

tasks:
  build-assets:
    command: bun --bun assetpack -c @files(wrapper-assetpack)
    options:
      internal: true
      cache: false
  build-sources:
    command: bun --bun rspack build
    options:
      internal: true
      cache: false
  build:
    toolchains: ["bun"]
    deps:
      - ^:build
      - ~:build-assets
      - ~:build-sources
    inputs:
      - "@group(wrapper-sources)"

  dev-assets:
    command: bun --bun assetpack -w -c @files(wrapper-assetpack)
    options:
      persistent: true
      outputStyle: stream
      internal: true
  dev-sources:
    command: bun --bun rspack serve
    options:
      persistent: true
      outputStyle: stream
      internal: true
  dev:
    toolchains: ["bun"]
    deps:
      - ^:dev
      - ~:dev-assets
      - ~:dev-sources
    options:
      persistent: true
    inputs:
      - "@group(wrapper-sources)"
