inheritedBy:
  layers: ["tool"]

tasks:
  build-assets:
    command: bunx assetpack -c @files(wrapper-assetpack)
    options:
      internal: true
  build-sources:
    command: bunx rspack build
    options:
      internal: true
  build:
    toolchains: ['bun']
    # TODO should i collect output?
    deps:
      - ^:build
      - ~:build-assets
      - ~:build-sources
    inputs:
      - "@group(wrapper-sources)"

  dev-assets:
    command: bunx assetpack -w -c @files(wrapper-assetpack)
    options:
      persistent: true
      outputStyle: stream
      internal: true
  dev-sources:
    command: bunx rspack serve
    options:
      persistent: true
      outputStyle: stream
      internal: true
  dev:
    toolchains: ['bun']
    deps:
      - ^:dev
      - ~:dev-assets
      - ~:dev-sources
    options:
      persistent: true
    inputs:
      - "@group(wrapper-sources)"
  
  assemble:
    script: |
      bunx moon run '#game:build'
      bunx moon run games-wrapper:build -f

